services:
  - type: web
    name: airbnb-backend
    env: node
    region: oregon

    plan: free

    buildCommand: "npm install"
    startCommand: "node app.js"

    envVars:
      - key: MONGO_URI
        sync: false   # set inside Render Dashboard
      - key: PORT
        value: 10000  # Render assigns correct port automatically

    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
